version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword   # ここで設定したパスワードを使用
      - DB_NAME=yourdbname
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword   # rootユーザーのパスワードを設定
      MYSQL_DATABASE: yourdbname          # 任意のデータベース名
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root                     # rootユーザーを使用
      PMA_PASSWORD: yourpassword         # rootユーザーのパスワード
      MYSQL_ROOT_PASSWORD: yourpassword  # 必要に応じて
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: